export const genres = [
  { id: 28, genre: "Action", color: "red" },
  { id: 12, genre: "Adventure", color: "orange" },
  { id: 16, genre: "Animation", color: "blue" },
  { id: 99, genre: "Documentary", color: "olive" },
  { id: 35, genre: "Comedy", color: "yellow" },
  { id: 80, genre: "Crime", color: "brown" },
  { id: 18, genre: "Drama", color: "orange" },
  { id: 10751, genre: "Family", color: "green" },
  { id: 14, genre: "Fantasy", color: "violet" },
  { id: 36, genre: "History", color: "brown" },
  { id: 27, genre: "Horror", color: "dark" },
  { id: 10402, genre: "Music", color: "pink" },
  { id: 9648, genre: "Mystery", color: "grey" },
  { id: 10749, genre: "Romance", color: "red" },
  { id: 878, genre: "Sci-Fi", color: "teal" },
  { id: 10770, genre: "Tv-movie", color: "violet" },
  { id: 53, genre: "Thriller", color: "grey" },
  { id: 10752, genre: "War", color: "vk" },
  { id: 37, genre: "Western", color: "green" },
];
